version: 1.3.1-b{build}
before_build:
- ps: nuget restore
build:
  project: Bud.TaskGraph.sln
  verbosity: minimal
before_package:
  - ps: 'cd Bud.TaskGraph; nuget pack Bud.TaskGraph.csproj'
artifacts:
  - path: Bud.TaskGraph/bin/Debug/Bud.TaskGraph.dll
    name: Bud.TaskGraph.dll
  - path: Bud.TaskGraph/bin/Debug/Bud.TaskGraph.xml
    name: Bud.TaskGraph.xml
  - path: 'Bud.TaskGraph/*.nupkg'
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
deploy:
  provider: NuGet
  api_key:
    secure: vHH6XlHbTmh514SHTC2RTHVZmB+Tv+7WkhGT7Jz+ctyJyYfa9CbSukRVqYhWSh3e
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
